const telas=[
 {titulo:'Visão Executiva',sub:'Pulso do negócio em uma única tela',dados:[['Beneficiários ativos',DADOS.geral.beneficiarios,'▲ 4,8% vs. mês anterior'],['Novas adesões',DADOS.geral.adesoes,'▲ 12,4%'],['Receita MTD',DADOS.geral.receita,'▲ 7,1%'],['Meta comercial',DADOS.geral.meta,'8 p.p. para a meta']]},
 {titulo:'Performance Comercial',sub:'Conversão, contratos e geração de receita',dados:[['Vendas MTD',DADOS.comercial.vendas,'▲ 9,2%'],['Novos contratos',DADOS.comercial.contratos,'▲ 5 contratos'],['Ticket médio',DADOS.comercial.ticket,'▲ 3,7%'],['Pipeline',DADOS.comercial.pipeline,'Cobertura 2,4x']]},
 {titulo:'Financeiro',sub:'Saúde financeira e qualidade da receita',dados:[['Receita MTD',DADOS.financeiro.receita,'▲ 7,1%'],['Recebimentos',DADOS.financeiro.recebimentos,'92,3% da receita'],['Inadimplência',DADOS.financeiro.inadimplencia,'▼ 0,4 p.p.'],['Margem',DADOS.financeiro.margem,'▲ 1,2 p.p.']]},
 {titulo:'Beneficiários',sub:'Crescimento, retenção e base ativa',dados:[['Ativos',DADOS.beneficiarios.ativos,'▲ 4,8%'],['Novos no mês',DADOS.beneficiarios.novos,'▲ 12,4%'],['Cancelamentos',DADOS.beneficiarios.cancelamentos,'▼ 8,0%'],['Churn',DADOS.beneficiarios.churn,'Dentro da meta']]},
 {titulo:'Operação & Atendimento',sub:'Eficiência operacional e experiência',dados:[['Chamados',DADOS.atendimento.chamados,'Mês atual'],['Resolvidos',DADOS.atendimento.resolvidos,'94,3%'],['SLA',DADOS.atendimento.sla,'Meta ≥ 95%'],['Tempo médio',DADOS.atendimento.tma,'▼ 22s']]},
 {titulo:'Saúde & Rede',sub:'Utilização e capacidade da rede',dados:[['Consultas',DADOS.saude.consultas,'▲ 6,2%'],['Exames',DADOS.saude.exames,'▲ 4,1%'],['Pontos da rede',DADOS.saude.rede,'+12 no trimestre'],['Custo médio',DADOS.saude.custo,'▼ 2,3%']]}
];
let atual=0,rodando=true,timer;
const dashboard=document.getElementById('dashboard');
function render(){const t=telas[atual];dashboard.innerHTML=`<section class="title"><div><h1>${t.titulo}</h1><p>${t.sub}</p></div><small>Última atualização: agora</small></section><section class="grid">${t.dados.map((d,i)=>`<article class="card"><div class="label">${d[0]}</div><div class="value">${d[1]}</div><div class="trend">${d[2]}</div>${i===3&&t.titulo==='Visão Executiva'?'<div class="progress"><i style="width:92%"></i></div>':''}</article>`).join('')}<article class="card wide"><div class="label">Evolução dos últimos 8 períodos</div><div class="bars">${DADOS.meses.map((v,i)=>`<div class="bar" style="height:${v}%"><span>P${i+1}</span></div>`).join('')}</div></article><article class="card wide"><div class="label">Leitura executiva</div><div class="value" style="font-size:24px">Operação estável</div><p style="color:var(--muted);line-height:1.6">Indicadores simulados apontam crescimento da base, SLA acima da meta e evolução comercial positiva. Prioridade: fechamento dos 8 p.p. restantes da meta.</p></article></section>`;document.getElementById('pageLabel').textContent=`${atual+1}/${telas.length}`}
function mover(n){atual=(atual+n+telas.length)%telas.length;render();reiniciar()}
function reiniciar(){clearInterval(timer);if(rodando)timer=setInterval(()=>mover(1),15000)}
document.getElementById('prev').onclick=()=>mover(-1);document.getElementById('next').onclick=()=>mover(1);document.getElementById('pause').onclick=e=>{rodando=!rodando;e.target.textContent=rodando?'Ⅱ':'▶';reiniciar()};
document.getElementById('alerts').textContent='● '+DADOS.alertas.join('   •   ');
setInterval(()=>document.getElementById('clock').textContent=new Date().toLocaleString('pt-BR'),1000);render();reiniciar();